name: ci
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 
      - name: Install Expo CLI
        run: npm install -g expo-cli
 
      - name: Install Dependencies
        run: npm install
 
      - name: Authenticate with Expo
        run: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
 
      - name: Build iOS Project
        run: npx expo build:ios --non-interactive
 
      - name: Build Android Project
        run: npx expo build:android --non-interactive
 
      - name: Build Web Project
        run: npx expo build:web --non-interactive